name: Build and Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Deploy to Raspberry Pi
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          port: ${{ secrets.RPI_PORT }}
          key: ${{ secrets.RPI_PRIVATE_KEY }}
          source: "dist/*"
          target: "${{ secrets.RPI_PATH }}"

      - name: Restart app on Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          port: ${{ secrets.RPI_PORT }}
          key: ${{ secrets.RPI_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.RPI_PATH }}/..
            pm2 restart neon-arcade || echo "No PM2 process found"
